#!/usr/bin/env bash
# Sourced by startup-app.sh from /opt/gow/startup.d/ (kodi-style), as user 'retro', just
# before the compositor starts. Prepares SoH's per-user data home and decides the launch
# argument (exported as SOH_ROM_ARG, consumed by /opt/soh/launch-soh.sh). UNPRIVILEGED.
#
# NOTE: this file is *sourced*, not executed — it runs under startup-app.sh's `set -e` and
# must not change shell options permanently. Only SOH_ROM_ARG is exported onward.
#
# Data model (three places):
#   - Image bundle (/opt/soh/usr/bin) read-only: binary + soh.o2r + assets + gamecontrollerdb.txt.
#                                    SoH locates these in the bundle itself. /etc/cont-init.d/
#                                    40-soh-bundle-links.sh (root) ALSO bridges oot.o2r/oot-mq.o2r
#                                    into the bundle -> the shared dir, so the home needs no o2r symlink.
#   - SHIP_HOME  ($HOME = /home/retro, from the image ENV) PER-USER: SoH reads/writes config,
#                                    saves, logs, mods and the extraction output here.
#   - SHARED_DIR (/roms)             SHARED mount you provide: the ROM (.z64) and the COMMON
#                                    oot.o2r reused by every profile (+ mods/).

WORK_DIR="${SHIP_HOME:-$HOME}"
SHARED_DIR="${SOH_SHARED:-/roms}"
MARKER="$SHARED_DIR/.soh-o2r-version"
IMAGE_VER="${SOH_VERSION:-unknown}"
ROM_PATH=""

log() { echo "[SoH] $*"; }
major() { printf '%s' "${1%%.*}"; }

# Shared helpers: fsize, publish_file, publish_string, promote_o2r (atomic temp+rename).
# shellcheck source=/dev/null
source /opt/soh/soh-lib.sh

mkdir -p "$WORK_DIR"
cd "$WORK_DIR"

# Seed default settings on first run (per-user). Copy only if absent, so the user's own
# changes persist across launches.
if [ ! -f shipofharkinian.json ] && [ -f /cfg/shipofharkinian.json ]; then
  log "Seeding default shipofharkinian.json from /cfg."
  cp /cfg/shipofharkinian.json shipofharkinian.json
fi

# Nothing archive-related is symlinked into the home anymore: soh.o2r/assets/gamecontrollerdb.txt
# are served from the bundle, and oot.o2r/oot-mq.o2r are bridged into the bundle by the cont-init
# script. Clean up any home bridges left by older image versions (symlinks only, never real files —
# a freshly-generated real oot.o2r awaiting promotion is NOT a symlink, so it's preserved).
for bridge in soh.o2r oot.o2r oot-mq.o2r assets gamecontrollerdb.txt; do
  if [ -L "$bridge" ]; then rm -f "$bridge"; fi
done
shopt -s nullglob
for bridge in *.z64 *.n64 *.zip; do
  if [ -L "$bridge" ]; then rm -f "$bridge"; fi
done
shopt -u nullglob

# Locate the ROM in the shared dir (only needed if there's no oot.o2r yet). We pass it to SoH
# by path (SOH_ROM_ARG) for extraction -> no symlink in the home needed.
have_rom=0
if [ -d "$SHARED_DIR" ]; then
  shopt -s nullglob
  for rom in "$SHARED_DIR"/*.z64 "$SHARED_DIR"/*.n64 "$SHARED_DIR"/*.zip; do
    have_rom=1
    ROM_PATH="$rom"
  done
  shopt -u nullglob
fi

# Stale check: oot.o2r is a DERIVED artifact we keep current (you provide only the .z64).
# If the shared oot.o2r was generated by a different MAJOR version (marker), drop it (and the
# per-user symlinks to it) so SoH regenerates it from the ROM this launch. Sessions already
# reading it keep their open fd (the data survives the unlink); new sessions regenerate.
if [ -e "$SHARED_DIR/oot.o2r" ] && [ -f "$MARKER" ]; then
  stored="$(cat "$MARKER" 2>/dev/null || echo unknown)"
  if [ "$(major "$stored")" != "$(major "$IMAGE_VER")" ]; then
    if [ -w "$SHARED_DIR" ]; then
      log "Shared oot.o2r is from an older MAJOR ($stored vs $IMAGE_VER) -> removing to regenerate from the ROM."
      rm -f "$SHARED_DIR/oot.o2r" "$SHARED_DIR/oot-mq.o2r" "$MARKER"
      rm -f oot.o2r oot-mq.o2r
    else
      log "WARNING: shared oot.o2r is from an older MAJOR ($stored vs $IMAGE_VER) but $SHARED_DIR is read-only; can't regenerate. Make it writable."
    fi
  fi
fi

# Fallback promotion: if an EARLIER session left a real oot.o2r in the home (e.g. it was
# extracted while /roms was read-only), promote it now. The MAIN promotion happens in
# launch-soh.sh right after extraction (same session). No-op in steady state.
promote_o2r

# Mods: symlink provided mod archives from the shared dir into the per-user mods folder.
# Symlink (not copy: would duplicate big packs per profile; not hardlink: can't cross the
# shared->home mount boundary). Enabling/disabling is a per-user config toggle that persists.
mkdir -p mods
shopt -s nullglob
# Prune dangling mod symlinks (e.g. a mod that was removed from the shared dir).
for link in mods/*; do
  if [ -L "$link" ] && [ ! -e "$link" ]; then rm -f "$link"; fi
done
if [ -d "$SHARED_DIR/mods" ]; then
  for mod in "$SHARED_DIR"/mods/*.o2r "$SHARED_DIR"/mods/*.otr; do
    ln -sf "$mod" "mods/$(basename "$mod")"
  done
fi
shopt -u nullglob

# Decide the launch argument (consumed by launch-soh.sh):
#   - oot.o2r available -> no arg  => SoH starts directly, ZERO prompts.
#   - no oot.o2r + ROM  -> pass the ROM; launch-soh.sh extracts hands-free (background + kill +
#     relaunch) and promotes the result. Exported so the ROM path stays quoted (launcher/sway
#     would split it on spaces).
if [ -e "$SHARED_DIR/oot.o2r" ] || [ -e oot.o2r ]; then
  log "oot.o2r available (shared bundle bridge) -> launching without prompts."
  export SOH_ROM_ARG=""
elif [ -n "$ROM_PATH" ]; then
  log "No common oot.o2r -> will pass the ROM ($ROM_PATH); SoH extracts it with a single confirm."
  export SOH_ROM_ARG="$ROM_PATH"
else
  log "ERROR: no common oot.o2r and no ROM in $SHARED_DIR."
  log "       Copy your ROM (OoT NTSC 1.0 US, .z64) or an already-generated oot.o2r to the shared folder."
  export SOH_ROM_ARG=""
fi
