#!/usr/bin/env bash
# Sourced by startup-app.sh from /opt/gow/startup.d/ (kodi-style), as user 'retro', just
# before the compositor starts. Prepares 2S2H's per-user data home and decides the launch
# argument (exported as S2H_ROM_ARG, consumed by /opt/2s2h/launch-2s2h.sh). UNPRIVILEGED.
#
# NOTE: this file is *sourced*, not executed — it runs under startup-app.sh's `set -e` and
# must not change shell options permanently. Only S2H_ROM_ARG is exported onward.
#
# Data model (three places):
#   - Image bundle (/opt/2s2h/usr/bin) read-only: binary + 2ship.o2r + assets + gamecontrollerdb.txt.
#                                    2S2H locates these in the bundle itself. /etc/cont-init.d/
#                                    40-2s2h-bundle-links.sh (root) ALSO bridges mm.o2r into the
#                                    bundle -> the shared dir, so the home needs no o2r symlink.
#   - SHIP_HOME  ($HOME = /home/retro, from the image ENV) PER-USER: 2S2H reads/writes config,
#                                    saves, logs, mods and the extraction output here.
#   - SHARED_DIR (/roms)             SHARED mount you provide: the ROM (.z64) and the COMMON
#                                    mm.o2r reused by every profile (+ mods/).
#
# Majora's Mask has no Master Quest, so there's a single ROM archive: mm.o2r.

WORK_DIR="${SHIP_HOME:-$HOME}"
SHARED_DIR="${S2H_SHARED:-/roms}"
MARKER="$SHARED_DIR/.2s2h-o2r-version"
IMAGE_VER="${S2H_VERSION:-unknown}"
ROM_PATH=""

log() { echo "[2S2H] $*"; }
major() { printf '%s' "${1%%.*}"; }

# Shared helpers: fsize, publish_file, publish_string, promote_o2r (atomic temp+rename).
# shellcheck source=/dev/null
source /opt/2s2h/2s2h-lib.sh

mkdir -p "$WORK_DIR"
cd "$WORK_DIR"

# Seed default settings on first run (per-user). Copy only if absent, so the user's own
# changes persist across launches. Inert until a 2ship2harkinian.json is shipped in /cfg
# (see the Dockerfile note) — boot once, configure, then commit that JSON to configs/.
if [ ! -f 2ship2harkinian.json ] && [ -f /cfg/2ship2harkinian.json ]; then
  log "Seeding default 2ship2harkinian.json from /cfg."
  cp /cfg/2ship2harkinian.json 2ship2harkinian.json
fi

# Nothing archive-related is symlinked into the home anymore: 2ship.o2r/assets/gamecontrollerdb.txt
# are served from the bundle, and mm.o2r is bridged into the bundle by the cont-init script.
# Clean up any home bridges left by older image versions (symlinks only, never real files — a
# freshly-generated real mm.o2r awaiting promotion is NOT a symlink, so it's preserved).
for bridge in 2ship.o2r mm.o2r assets gamecontrollerdb.txt; do
  if [ -L "$bridge" ]; then rm -f "$bridge"; fi
done
shopt -s nullglob
for bridge in *.z64 *.n64 *.zip; do
  if [ -L "$bridge" ]; then rm -f "$bridge"; fi
done
shopt -u nullglob

# Locate the ROM in the shared dir (only needed if there's no mm.o2r yet). We pass it to 2S2H
# by path (S2H_ROM_ARG) for extraction -> no symlink in the home needed.
have_rom=0
if [ -d "$SHARED_DIR" ]; then
  shopt -s nullglob
  for rom in "$SHARED_DIR"/*.z64 "$SHARED_DIR"/*.n64 "$SHARED_DIR"/*.zip; do
    have_rom=1
    ROM_PATH="$rom"
  done
  shopt -u nullglob
fi

# Stale check: mm.o2r is a DERIVED artifact we keep current (you provide only the .z64).
# If the shared mm.o2r was generated by a different MAJOR version (marker), drop it (and the
# per-user symlinks to it) so 2S2H regenerates it from the ROM this launch. Sessions already
# reading it keep their open fd (the data survives the unlink); new sessions regenerate.
if [ -e "$SHARED_DIR/mm.o2r" ] && [ -f "$MARKER" ]; then
  stored="$(cat "$MARKER" 2>/dev/null || echo unknown)"
  if [ "$(major "$stored")" != "$(major "$IMAGE_VER")" ]; then
    if [ -w "$SHARED_DIR" ]; then
      log "Shared mm.o2r is from an older MAJOR ($stored vs $IMAGE_VER) -> removing to regenerate from the ROM."
      rm -f "$SHARED_DIR/mm.o2r" "$MARKER"
      rm -f mm.o2r
    else
      log "WARNING: shared mm.o2r is from an older MAJOR ($stored vs $IMAGE_VER) but $SHARED_DIR is read-only; can't regenerate. Make it writable."
    fi
  fi
fi

# Fallback promotion: if an EARLIER session left a real mm.o2r in the home (e.g. it was
# extracted while /roms was read-only), promote it now. The MAIN promotion happens in
# launch-2s2h.sh right after extraction (same session). No-op in steady state.
promote_o2r

# Mods: symlink provided mod archives from the shared dir into the per-user mods folder.
# Symlink (not copy: would duplicate big packs per profile; not hardlink: can't cross the
# shared->home mount boundary). Enabling/disabling is a per-user config toggle that persists.
mkdir -p mods
shopt -s nullglob
# Prune dangling mod symlinks (e.g. a mod that was removed from the shared dir).
for link in mods/*; do
  if [ -L "$link" ] && [ ! -e "$link" ]; then rm -f "$link"; fi
done
if [ -d "$SHARED_DIR/mods" ]; then
  for mod in "$SHARED_DIR"/mods/*.o2r "$SHARED_DIR"/mods/*.otr; do
    ln -sf "$mod" "mods/$(basename "$mod")"
  done
fi
shopt -u nullglob

# Decide the launch argument (consumed by launch-2s2h.sh):
#   - mm.o2r available -> no arg  => 2S2H starts directly, ZERO prompts.
#   - no mm.o2r + ROM  -> pass the ROM; launch-2s2h.sh extracts hands-free (background + kill +
#     relaunch) and promotes the result. Exported so the ROM path stays quoted (launcher/sway
#     would split it on spaces).
if [ -e "$SHARED_DIR/mm.o2r" ] || [ -e mm.o2r ]; then
  log "mm.o2r available (shared bundle bridge) -> launching without prompts."
  export S2H_ROM_ARG=""
elif [ -n "$ROM_PATH" ]; then
  log "No common mm.o2r -> will pass the ROM ($ROM_PATH); 2S2H extracts it with a single confirm."
  export S2H_ROM_ARG="$ROM_PATH"
else
  log "ERROR: no common mm.o2r and no ROM in $SHARED_DIR."
  log "       Copy your ROM (Majora's Mask NTSC US, .z64) or an already-generated mm.o2r to the shared folder."
  export S2H_ROM_ARG=""
fi
