#!/usr/bin/env bash
# Sourced by startup-app.sh from /opt/gow/startup.d/ (kodi-style), as user 'retro', just before
# the compositor starts. Prepares Ghostship's per-user data home and, when there's no sm64.o2r
# yet, exports GHOSTSHIP_ROM_PATH (the ROM that launch-ghostship.sh extracts from). UNPRIVILEGED.
#
# NOTE: this file is *sourced*, not executed — it runs under startup-app.sh's `set -e` and must
# not change shell options permanently. Only GHOSTSHIP_ROM_PATH is exported onward.
#
# Data model (three places):
#   - Image bundle (/opt/ghostship/usr/bin) read-only: binary + ghostship.o2r + config.yml +
#                                    assets + gamecontrollerdb.txt. Ghostship finds ghostship.o2r
#                                    here via LocateFileAcrossAppDirs (it checks the bundle).
#   - SHIP_HOME  ($HOME = /home/retro, from the image ENV) PER-USER: Ghostship reads/writes config,
#                                    saves, logs, mods AND reads sm64.o2r here. sm64.o2r is resolved
#                                    with GetPathRelativeToAppDirectory (the data dir ONLY, not the
#                                    bundle), so the shared copy is symlinked INTO this home.
#   - SHARED_DIR (/roms)             SHARED mount you provide: the ROM (.z64) and the COMMON
#                                    sm64.o2r reused by every profile (+ mods/).
#
# Super Mario 64 has a single ROM archive: sm64.o2r.

WORK_DIR="${SHIP_HOME:-$HOME}"
SHARED_DIR="${GHOSTSHIP_SHARED:-/roms}"
MARKER="$SHARED_DIR/.ghostship-o2r-version"
IMAGE_VER="${GHOSTSHIP_VERSION:-unknown}"
ROM_PATH=""

log() { echo "[Ghostship] $*"; }
major() { printf '%s' "${1%%.*}"; }

# Shared helpers: publish_file, publish_string, promote_o2r, rom_supported, torch_extract.
# shellcheck source=/dev/null
source /opt/ghostship/ghostship-lib.sh

mkdir -p "$WORK_DIR"
cd "$WORK_DIR"

# Seed default settings on first run (per-user). Copy only if absent, so the user's own
# changes persist across launches.
if [ ! -f ghostship.cfg.json ] && [ -f /cfg/ghostship.cfg.json ]; then
  log "Seeding default ghostship.cfg.json from /cfg."
  cp /cfg/ghostship.cfg.json ghostship.cfg.json
fi

# ghostship.o2r/config.yml/assets/gamecontrollerdb.txt are served from the bundle, so the home
# needs no symlink for those — prune any left by older image versions (symlinks only, never real
# files). sm64.o2r is handled separately below (it must live in the home), so it's NOT pruned here.
for bridge in ghostship.o2r config.yml assets gamecontrollerdb.txt; do
  if [ -L "$bridge" ]; then rm -f "$bridge"; fi
done
shopt -s nullglob
for bridge in *.z64 *.n64 *.v64 *.zip; do
  if [ -L "$bridge" ]; then rm -f "$bridge"; fi
done
shopt -u nullglob

# Locate the ROM in the shared dir (only needed if there's no sm64.o2r yet). We hand its path to
# launch-ghostship.sh (GHOSTSHIP_ROM_PATH), which builds sm64.o2r from it headlessly -> no home
# symlink.
if [ -d "$SHARED_DIR" ]; then
  shopt -s nullglob
  for rom in "$SHARED_DIR"/*.z64 "$SHARED_DIR"/*.n64 "$SHARED_DIR"/*.v64; do
    ROM_PATH="$rom"
  done
  shopt -u nullglob
fi

# Stale check: sm64.o2r is a DERIVED artifact we keep current (you provide only the .z64).
# If the shared sm64.o2r was generated by a different MAJOR version (marker), drop it so
# Ghostship regenerates it from the ROM this launch. Sessions already reading it keep their open
# fd (the data survives the unlink); new sessions regenerate.
if [ -e "$SHARED_DIR/sm64.o2r" ] && [ -f "$MARKER" ]; then
  stored="$(cat "$MARKER" 2>/dev/null || echo unknown)"
  if [ "$(major "$stored")" != "$(major "$IMAGE_VER")" ]; then
    if [ -w "$SHARED_DIR" ]; then
      log "Shared sm64.o2r is from an older MAJOR ($stored vs $IMAGE_VER) -> removing to regenerate from the ROM."
      rm -f "$SHARED_DIR/sm64.o2r" "$MARKER"
      rm -f sm64.o2r
    else
      log "WARNING: shared sm64.o2r is from an older MAJOR ($stored vs $IMAGE_VER) but $SHARED_DIR is read-only; can't regenerate. Make it writable."
    fi
  fi
fi

# Fallback promotion: if an EARLIER session left a real sm64.o2r in the home (e.g. it was
# extracted while /roms was read-only), promote it now. The MAIN promotion happens in
# launch-ghostship.sh right after extraction (same session). No-op in steady state.
promote_o2r

# Make the shared sm64.o2r visible to the game by symlinking it into the home (the data dir is the
# ONLY place Ghostship looks for it). Prune a stale/dangling link first.
if [ -L sm64.o2r ] && [ ! -e sm64.o2r ]; then rm -f sm64.o2r; fi
ensure_o2r_in_home

# Mods: symlink provided mod archives from the shared dir into the per-user mods folder.
# Symlink (not copy: would duplicate big packs per profile; not hardlink: can't cross the
# shared->home mount boundary). Enabling/disabling is a per-user toggle that persists.
mkdir -p mods
shopt -s nullglob
# Prune dangling mod symlinks (e.g. a mod that was removed from the shared dir).
for link in mods/*; do
  if [ -L "$link" ] && [ ! -e "$link" ]; then rm -f "$link"; fi
done
if [ -d "$SHARED_DIR/mods" ]; then
  for mod in "$SHARED_DIR"/mods/*.o2r "$SHARED_DIR"/mods/*.otr; do
    ln -sf "$mod" "mods/$(basename "$mod")"
  done
fi
shopt -u nullglob

# Decide what launch-ghostship.sh does (GHOSTSHIP_ROM_PATH, exported so the path stays quoted —
# launcher/sway would otherwise split it on spaces):
#   - sm64.o2r available -> empty  => Ghostship starts directly, ZERO prompts.
#   - no sm64.o2r + ROM  -> the ROM path; launch builds sm64.o2r headlessly via the bundled Torch
#                           CLI and publishes it back (no in-app GUI extractor, no clicks).
if [ -e "$SHARED_DIR/sm64.o2r" ] || [ -e sm64.o2r ]; then
  log "sm64.o2r present (linked into the home) -> launching without prompts."
  export GHOSTSHIP_ROM_PATH=""
elif [ -n "$ROM_PATH" ]; then
  log "No common sm64.o2r -> launch will build it from the ROM ($ROM_PATH) headlessly."
  export GHOSTSHIP_ROM_PATH="$ROM_PATH"
else
  log "ERROR: no common sm64.o2r and no ROM in $SHARED_DIR."
  log "       Copy your ROM (Super Mario 64 US or JP, .z64) or a generated sm64.o2r to the shared folder."
  export GHOSTSHIP_ROM_PATH=""
fi
