#!/usr/bin/env bash
# Sourced by startup-app.sh from /opt/gow/startup.d/ (kodi-style), as user 'retro', just
# before the compositor starts. Prepares SoH's per-user data home and decides the launch
# argument (exported as SOH_ROM_ARG, consumed by /opt/soh/launch-soh.sh). UNPRIVILEGED.
#
# NOTE: this file is *sourced*, not executed — it runs under startup-app.sh's `set -e` and
# must not change shell options permanently. Only SOH_ROM_ARG is exported onward.
#
# Data model (three places):
#   - GAME_DIR   (/opt/soh/usr/bin)  read-only baked files: binary, soh.o2r, assets.
#   - SHIP_HOME  ($HOME = /home/retro, from the image ENV) PER-USER: SoH reads/writes config,
#                                    saves, logs, mods and the extraction output here.
#   - SHARED_DIR (/mnt/soh-shared)   SHARED mount you provide: the ROM (.z64) and the COMMON
#                                    oot.o2r reused by every profile.

GAME_DIR=/opt/soh/usr/bin
WORK_DIR="${SHIP_HOME:-$HOME}"
SHARED_DIR="${SOH_SHARED:-/mnt/soh-shared}"
MARKER="$SHARED_DIR/.soh-o2r-version"
IMAGE_VER="${SOH_VERSION:-unknown}"
ROM_PATH=""

log() { echo "[SoH] $*"; }
major() { printf '%s' "${1%%.*}"; }

# Atomic publish to the SHARED dir (temp + rename): a concurrent session never sees a
# half-written file, and two simultaneous publishes each write a COMPLETE file.
publish() { # <src-file> <dest-path>
  local src="$1" dest="$2" tmp
  tmp="$(mktemp "${dest}.XXXXXX" 2>/dev/null)" || return 1
  if cp -f "$src" "$tmp" 2>/dev/null && mv -f "$tmp" "$dest" 2>/dev/null; then return 0; fi
  rm -f "$tmp" 2>/dev/null; return 1
}
publish_str() { # <string> <dest-path>
  local str="$1" dest="$2" tmp
  tmp="$(mktemp "${dest}.XXXXXX" 2>/dev/null)" || return 1
  if printf '%s\n' "$str" > "$tmp" 2>/dev/null && mv -f "$tmp" "$dest" 2>/dev/null; then return 0; fi
  rm -f "$tmp" 2>/dev/null; return 1
}

mkdir -p "$WORK_DIR"
cd "$WORK_DIR"

# Seed default settings on first run (per-user). Copy only if absent, so the user's own
# changes persist across launches.
if [ ! -f shipofharkinian.json ] && [ -f /cfg/shipofharkinian.json ]; then
  log "Seeding default shipofharkinian.json from /cfg."
  cp /cfg/shipofharkinian.json shipofharkinian.json
fi

# Read-only baked files -> home. (soh.o2r/assets also resolve from the image bundle via
# LocateFileAcrossAppDirs, but we link them too as belt-and-suspenders.)
ln -sfn "$GAME_DIR/assets" assets
ln -sf  "$GAME_DIR/soh.o2r" soh.o2r
if [ -f "$GAME_DIR/gamecontrollerdb.txt" ]; then
  ln -sf "$GAME_DIR/gamecontrollerdb.txt" gamecontrollerdb.txt
fi

# Shared ROM -> home (SoH validates by hash; only used if there's no oot.o2r yet).
have_rom=0
if [ -d "$SHARED_DIR" ]; then
  shopt -s nullglob
  for rom in "$SHARED_DIR"/*.z64 "$SHARED_DIR"/*.n64 "$SHARED_DIR"/*.zip; do
    ln -sf "$rom" "./$(basename "$rom")"
    have_rom=1
    ROM_PATH="$rom"
  done
  shopt -u nullglob
fi

# Stale check: oot.o2r is a DERIVED artifact we keep current (you provide only the .z64).
# If the shared oot.o2r was generated by a different MAJOR version (marker), drop it (and the
# per-user symlinks to it) so SoH regenerates it from the ROM this launch. Sessions already
# reading it keep their open fd (the data survives the unlink); new sessions regenerate.
if [ -e "$SHARED_DIR/oot.o2r" ] && [ -f "$MARKER" ]; then
  stored="$(cat "$MARKER" 2>/dev/null || echo unknown)"
  if [ "$(major "$stored")" != "$(major "$IMAGE_VER")" ]; then
    if [ -w "$SHARED_DIR" ]; then
      log "Shared oot.o2r is from an older MAJOR ($stored vs $IMAGE_VER) -> removing to regenerate from the ROM."
      rm -f "$SHARED_DIR/oot.o2r" "$SHARED_DIR/oot-mq.o2r" "$MARKER"
      rm -f oot.o2r oot-mq.o2r
    else
      log "WARNING: shared oot.o2r is from an older MAJOR ($stored vs $IMAGE_VER) but $SHARED_DIR is read-only; can't regenerate. Make it writable."
    fi
  fi
fi

# Promote a per-user-generated oot.o2r to the shared dir so it becomes common.
if [ -d "$SHARED_DIR" ] && [ ! -e "$SHARED_DIR/oot.o2r" ] && [ -f oot.o2r ] && [ ! -L oot.o2r ] && [ -w "$SHARED_DIR" ]; then
  log "Promoting the generated oot.o2r to the shared dir (atomic)."
  publish oot.o2r "$SHARED_DIR/oot.o2r" || log "Promotion skipped (another session may have won the race)."
  if [ -f oot-mq.o2r ] && [ ! -L oot-mq.o2r ]; then publish oot-mq.o2r "$SHARED_DIR/oot-mq.o2r" || true; fi
  publish_str "$IMAGE_VER" "$MARKER" || true
fi

# Use the shared (common) oot.o2r: symlink it into the home, dropping any per-user copy.
# (Staleness was already handled above — if we reach here with a shared o2r, it's current.)
if [ -e "$SHARED_DIR/oot.o2r" ]; then
  rm -f oot.o2r oot-mq.o2r
  ln -sf "$SHARED_DIR/oot.o2r" oot.o2r
  if [ -e "$SHARED_DIR/oot-mq.o2r" ]; then ln -sf "$SHARED_DIR/oot-mq.o2r" oot-mq.o2r; fi
fi

# Mods: symlink provided mod archives from the shared dir into the per-user mods folder.
# Symlink (not copy: would duplicate big packs per profile; not hardlink: can't cross the
# shared->home mount boundary). Enabling/disabling is a per-user config toggle that persists.
mkdir -p mods
shopt -s nullglob
# Prune dangling mod symlinks (e.g. a mod that was removed from the shared dir).
for link in mods/*; do
  if [ -L "$link" ] && [ ! -e "$link" ]; then rm -f "$link"; fi
done
if [ -d "$SHARED_DIR/mods" ]; then
  for mod in "$SHARED_DIR"/mods/*.o2r "$SHARED_DIR"/mods/*.otr; do
    ln -sf "$mod" "mods/$(basename "$mod")"
  done
fi
shopt -u nullglob

# Decide the launch argument. SoH's extractor is GUI-driven (no headless mode):
#   - oot.o2r present  -> no arg  => ZERO prompts.
#   - no oot.o2r + ROM -> pass the ROM => ONE confirm popup, then extract + promote.
# Exported so launch-soh.sh execs the binary with the ROM path quoted (launcher/sway would
# split an unquoted path on spaces).
if [ -e oot.o2r ]; then
  log "oot.o2r present -> launching without prompts."
  export SOH_ROM_ARG=""
elif [ -n "$ROM_PATH" ]; then
  log "No common oot.o2r -> will pass the ROM ($ROM_PATH); SoH extracts it with a single confirm."
  export SOH_ROM_ARG="$ROM_PATH"
else
  log "ERROR: no common oot.o2r and no ROM in $SHARED_DIR."
  log "       Copy your ROM (OoT NTSC 1.0 US, .z64) or an already-generated oot.o2r to the shared folder."
  export SOH_ROM_ARG=""
fi
