#!/usr/bin/env bash
# Sourced by startup-app.sh from /opt/gow/startup.d/ (kodi-style), as user 'retro', just
# before the compositor starts. Prepares SoH's per-user data home and decides the launch
# argument (exported as SOH_ROM_ARG, consumed by /opt/soh/launch-soh.sh). UNPRIVILEGED.
#
# NOTE: this file is *sourced*, not executed — it runs under startup-app.sh's `set -e` and
# must not change shell options permanently. Only SOH_ROM_ARG is exported onward.
#
# Data model (three places):
#   - Image bundle (/opt/soh/usr/bin) read-only: binary + soh.o2r + assets + gamecontrollerdb.txt.
#                                    SoH locates these in the bundle itself. /etc/cont-init.d/
#                                    40-soh-bundle-links.sh (root) ALSO bridges oot.o2r/oot-mq.o2r
#                                    into the bundle -> the shared dir, so the home needs no o2r symlink.
#   - SHIP_HOME  ($HOME = /home/retro, from the image ENV) PER-USER: SoH reads/writes config,
#                                    saves, logs, mods and the extraction output here.
#   - SHARED_DIR (/roms)             SHARED mount you provide: the ROM (.z64) and the COMMON
#                                    oot.o2r reused by every profile (+ mods/).

WORK_DIR="${SHIP_HOME:-$HOME}"
SHARED_DIR="${SOH_SHARED:-/roms}"
MARKER="$SHARED_DIR/.soh-o2r-version"
IMAGE_VER="${SOH_VERSION:-unknown}"
ROM_PATH=""

log() { echo "[SoH] $*"; }
major() { printf '%s' "${1%%.*}"; }

# Atomic publish to the SHARED dir (temp + rename): a concurrent session never sees a
# half-written file, and two simultaneous publishes each write a COMPLETE file.
publish() { # <src-file> <dest-path>
  local src="$1" dest="$2" tmp
  tmp="$(mktemp "${dest}.XXXXXX" 2>/dev/null)" || return 1
  if cp -f "$src" "$tmp" 2>/dev/null && mv -f "$tmp" "$dest" 2>/dev/null; then return 0; fi
  rm -f "$tmp" 2>/dev/null; return 1
}
publish_str() { # <string> <dest-path>
  local str="$1" dest="$2" tmp
  tmp="$(mktemp "${dest}.XXXXXX" 2>/dev/null)" || return 1
  if printf '%s\n' "$str" > "$tmp" 2>/dev/null && mv -f "$tmp" "$dest" 2>/dev/null; then return 0; fi
  rm -f "$tmp" 2>/dev/null; return 1
}

mkdir -p "$WORK_DIR"
cd "$WORK_DIR"

# Seed default settings on first run (per-user). Copy only if absent, so the user's own
# changes persist across launches.
if [ ! -f shipofharkinian.json ] && [ -f /cfg/shipofharkinian.json ]; then
  log "Seeding default shipofharkinian.json from /cfg."
  cp /cfg/shipofharkinian.json shipofharkinian.json
fi

# Nothing archive-related is symlinked into the home anymore: soh.o2r/assets/gamecontrollerdb.txt
# are served from the bundle, and oot.o2r/oot-mq.o2r are bridged into the bundle by the cont-init
# script. Clean up any home bridges left by older image versions (symlinks only, never real files —
# a freshly-generated real oot.o2r awaiting promotion is NOT a symlink, so it's preserved).
for bridge in soh.o2r oot.o2r oot-mq.o2r assets gamecontrollerdb.txt; do
  if [ -L "$bridge" ]; then rm -f "$bridge"; fi
done
shopt -s nullglob
for bridge in *.z64 *.n64 *.zip; do
  if [ -L "$bridge" ]; then rm -f "$bridge"; fi
done
shopt -u nullglob

# Locate the ROM in the shared dir (only needed if there's no oot.o2r yet). We pass it to SoH
# by path (SOH_ROM_ARG) for extraction -> no symlink in the home needed.
have_rom=0
if [ -d "$SHARED_DIR" ]; then
  shopt -s nullglob
  for rom in "$SHARED_DIR"/*.z64 "$SHARED_DIR"/*.n64 "$SHARED_DIR"/*.zip; do
    have_rom=1
    ROM_PATH="$rom"
  done
  shopt -u nullglob
fi

# Stale check: oot.o2r is a DERIVED artifact we keep current (you provide only the .z64).
# If the shared oot.o2r was generated by a different MAJOR version (marker), drop it (and the
# per-user symlinks to it) so SoH regenerates it from the ROM this launch. Sessions already
# reading it keep their open fd (the data survives the unlink); new sessions regenerate.
if [ -e "$SHARED_DIR/oot.o2r" ] && [ -f "$MARKER" ]; then
  stored="$(cat "$MARKER" 2>/dev/null || echo unknown)"
  if [ "$(major "$stored")" != "$(major "$IMAGE_VER")" ]; then
    if [ -w "$SHARED_DIR" ]; then
      log "Shared oot.o2r is from an older MAJOR ($stored vs $IMAGE_VER) -> removing to regenerate from the ROM."
      rm -f "$SHARED_DIR/oot.o2r" "$SHARED_DIR/oot-mq.o2r" "$MARKER"
      rm -f oot.o2r oot-mq.o2r
    else
      log "WARNING: shared oot.o2r is from an older MAJOR ($stored vs $IMAGE_VER) but $SHARED_DIR is read-only; can't regenerate. Make it writable."
    fi
  fi
fi

# Promote a freshly-generated oot.o2r (SoH wrote it into the home) to the shared dir so it
# becomes common, then drop the home copy — from now on the cont-init bundle symlink serves it.
if [ -d "$SHARED_DIR" ] && [ ! -e "$SHARED_DIR/oot.o2r" ] && [ -f oot.o2r ] && [ ! -L oot.o2r ] && [ -w "$SHARED_DIR" ]; then
  log "Promoting the generated oot.o2r to the shared dir (atomic)."
  if publish oot.o2r "$SHARED_DIR/oot.o2r"; then
    if [ -f oot-mq.o2r ] && [ ! -L oot-mq.o2r ]; then publish oot-mq.o2r "$SHARED_DIR/oot-mq.o2r" || true; fi
    publish_str "$IMAGE_VER" "$MARKER" || true
    rm -f oot.o2r oot-mq.o2r   # served by the bundle symlink now -> keep the home clean
  else
    log "Promotion skipped (another session may have won the race)."
  fi
fi

# No home symlink for oot.o2r: the cont-init bundle bridge makes SoH find it in /roms. If a
# previous session left a real oot.o2r in the home, it was promoted + removed just above.

# Mods: symlink provided mod archives from the shared dir into the per-user mods folder.
# Symlink (not copy: would duplicate big packs per profile; not hardlink: can't cross the
# shared->home mount boundary). Enabling/disabling is a per-user config toggle that persists.
mkdir -p mods
shopt -s nullglob
# Prune dangling mod symlinks (e.g. a mod that was removed from the shared dir).
for link in mods/*; do
  if [ -L "$link" ] && [ ! -e "$link" ]; then rm -f "$link"; fi
done
if [ -d "$SHARED_DIR/mods" ]; then
  for mod in "$SHARED_DIR"/mods/*.o2r "$SHARED_DIR"/mods/*.otr; do
    ln -sf "$mod" "mods/$(basename "$mod")"
  done
fi
shopt -u nullglob

# Decide the launch argument. SoH's extractor is GUI-driven (no headless mode):
#   - oot.o2r present  -> no arg  => ZERO prompts.
#   - no oot.o2r + ROM -> pass the ROM => ONE confirm popup, then extract + promote.
# Exported so launch-soh.sh execs the binary with the ROM path quoted (launcher/sway would
# split an unquoted path on spaces).
if [ -e "$SHARED_DIR/oot.o2r" ] || [ -e oot.o2r ]; then
  log "oot.o2r available (shared bundle bridge) -> launching without prompts."
  export SOH_ROM_ARG=""
elif [ -n "$ROM_PATH" ]; then
  log "No common oot.o2r -> will pass the ROM ($ROM_PATH); SoH extracts it with a single confirm."
  export SOH_ROM_ARG="$ROM_PATH"
else
  log "ERROR: no common oot.o2r and no ROM in $SHARED_DIR."
  log "       Copy your ROM (OoT NTSC 1.0 US, .z64) or an already-generated oot.o2r to the shared folder."
  export SOH_ROM_ARG=""
fi
